apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-demo-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/vanshika622/aws-k8s-secret-gitops
    path: .
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
